version: "3.9"

services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ollama:
  #   image: ollama/ollama:latest
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"  # expose for local debugging / model pulling
  #   volumes:
  #     - ollama:/root/.ollama
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=2h

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - mongodb
      # - ollama
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=ukrics
      # - OLLAMA_URL=http://ollama:11434/api/generate
      # - OLLAMA_MODEL=llava:7b
      - JWT_EXP_DAYS=7
    ports:
      - "8000:8000"
    volumes:
      - backend-uploads:/app/uploaded_images

  frontend:
    build:
      context: ./frontend-react
      args:
        # Use relative API calls proxied by nginx (/api -> backend)
        - VITE_API_BASE=
    restart: unless-stopped
    depends_on:
      - backend

  caddy:
    build: ./caddy
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      # - "443:443"  # enable when TLS is configured
    restart: unless-stopped

volumes:
  mongo-data:
  # ollama:
  backend-uploads:
